-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 14:29:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Quiroefficient` DEFAULT CHARACTER SET utf8 ;
USE `Quiroefficient` ;
-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiroefficient`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(50) NOT NULL,
  `passwd` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiroefficient`.`pacientes` (
  `idpacientes` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `eps` VARCHAR(45) NOT NULL,
  `edad` INT(3) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpacientes`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `cirujanos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiroefficient`.`cirujanos` (
  `idcirujanos` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcirujanos`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiroefficient`.`equipos` (
  `idequipos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `codserial` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idequipos`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `quirofanos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiroefficient`.`quirofanos` (
  `idquirofanos` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idquirofanos`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `indicadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiroefficient`.`indicadores` (
  `idindicadores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idquirofanos`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `cirugias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiroefficient`.`cirugias` (
  `idCirujias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFinal` TIME NOT NULL,
  `duracionEstimada` TIME NOT NULL,
  `duracionReal` TIME NOT NULL,
  `detalles` VARCHAR(500) NOT NULL,
  `cancelacion` VARCHAR(45) NOT NULL,
  `motivoCancelacion` VARCHAR(45) NOT NULL,
  `idpaciente` INT NOT NULL,
  `idcirujano` INT NOT NULL,
  `idequipo` INT NOT NULL,
  `idquirofano` INT NOT NULL,
  PRIMARY KEY (`idCirujias`),
  INDEX `fk_cirujias_pacientes_idx` (`idpacientes` ASC) VISIBLE,
  INDEX `fk_cirujias_cirujanos1_idx` (`idcirujanos` ASC) VISIBLE,
  INDEX `fk_cirujias_equipos1_idx` (`idequipos` ASC) VISIBLE,
  INDEX `fk_cirujias_quirofanos1_idx` (`idquirofanos` ASC) VISIBLE,
  CONSTRAINT `fk_cirujias_pacientes`
    FOREIGN KEY (`idpacientes`)
    REFERENCES `pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cirujias_cirujanos1`
    FOREIGN KEY (`idcirujanos`)
    REFERENCES `cirujanos` (`idcirujanos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cirujias_equipos1`
    FOREIGN KEY (`idequipos`)
    REFERENCES `equipos` (`idequipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cirujias_quirofanos1`
    FOREIGN KEY (`idquirofanos`)
    REFERENCES `quirofanos` (`idquirofanos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
